spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kenneth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: Root
    driver-class-name: com.mysql.jdbc.Driver
